@URL=http://localhost:3000/users

### CRIAR USUARIO
POST {{URL}}
Content-Type: application/json

{
    "name": "Jeca",
    "email": "jeca@gmail.com",
    "password": "123123"
}

### Obter usuários
GET {{URL}}
Authorization: 1234

### Obter usuários
GET {{URL}}/68dd655db11d3a949a5704a7